# Generated by Django 5.1.2 on 2025-01-17 12:00

import Menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('trending', models.BooleanField(default=False)),
                ('img', models.ImageField(null=True, upload_to=Menu.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(blank=True, max_length=15, null=True)),
                ('carbs', models.CharField(blank=True, max_length=15, null=True)),
                ('proteins', models.CharField(blank=True, max_length=15, null=True)),
                ('fats', models.CharField(blank=True, max_length=15, null=True)),
                ('cholesterol', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=25, null=True)),
                ('trending', models.BooleanField(default=False)),
                ('img', models.ImageField(null=True, upload_to=Menu.models.getFileName)),
                ('actuall_price', models.IntegerField()),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
