# Generated by Django 5.1.2 on 2025-01-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalinfo',
            name='name',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Menu.catagory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nutritionalinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Menu.nutritionalinfo'),
            preserve_default=False,
        ),
    ]
